### ISSUE TITLE
Elements in the 'proof' section behave in unexpected ways

### ISSUE THREAD

**Issue by RieksJ** [w3c-ccg/vc-verifier-http-api#3]
I have created a VC using the [universal issuer tool](https://beta.uniissuer.io/), copied it, and pasted it in the verifier. Then I clicked the button 'Verify', and yes, it returned `true`.

Then I did some modifications in the `proof` section and observed the behavior of verification:
1. I changed the proof creation date `created` in the `proof` section (changed the timezone). The credential still verifies to `true`. In fact, I can change the contents of this field to anything I want. I had expected that to result in verification failure, or to another error.
2. If I change the contents of the `domain` field, e.g. to nulls, verification does not seem to terminate. I would have expected an error message here.
3. The contents of the `nonce` field can be tampered with as well - it doesn't matter what's in there.

**Comment by peacekeeper** [comment]
Hello @RieksJ thanks for your input.. Note that this repo here contains an open API definition for VC issuers. If you don't mind, I think we should discuss topics related to the API definition here, but discuss concrete implementations elsewhere.
